---
# zabbix: ver 4.2.8
# mysql : ver 5.7
# OS    : Amazon Linux 2


############################################################
# Common
############################################################
zabbix_repo_url: https://repo.zabbix.com/zabbix/4.2/rhel/7/x86_64/zabbix-release-4.2-2.el7.noarch.rpm
zabbix_login_user: "Admin"
zabbix_login_password: "zabbix"
zabbix_srever_url: "http://  <<zabbix server EIP>>  /zabbix/"

############################################################
# server 
############################################################
server:
  public_ip: ""
  private_ip: ""

  zabbix_packages:  # => server.packagesで使えるはず
    - zabbix-server-mysql
    - zabbix-web-mysql
    - zabbix-web-japanese
    - zabbix-agent
    # インラインで実行
  mysql_packages:
    - mysql
    - mysql-devel
    - MySQL-python

  db_name: "zabbix"
  db_user: "zabbix"
  db_password: "passwrod"
  rds_mysql_user: "myk"
  rds_mysql_password: "password"
  rds_endpoint: "myk-zabbix-rds.chame7ljk7b1.ap-northeast-1.rds.amazonaws.com"

  php_config:
    - regexp: '^;(date.timezone) =.*'
      line: '\1 = Asia/Tokyo'
    # - regexp:
    #   line:
    # withItems使用

  service:
    - zabbix-server
    - zabbix-agent
    - httpd


############################################################
# Proxy
############################################################
proxy:
  public_ip: ""
  private_ip: ""


############################################################
# Agent 
############################################################
agent:
  public_ip: ""
  private_ip: ""

  zabbix_packages:
    - zabbix-agent

  service:
    - zabbix-agent